export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const LOADING_PRODUCT_DONE = "LOADING_PRODUCT_DONE";
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE";
export const ORDER_PRODUCT_BY_PRICE = "ORDER_PRODUCT_BY_PRICE";
